# Generated by Django 4.1.7 on 2023-03-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_rename_sub_category_category_parent_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
    ]
