# Generated by Django 4.1.7 on 2023-03-24 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField(blank=True)),
                ('tomatoes', models.IntegerField(blank=True, default=None, null=True)),
                ('tomatoes_done', models.IntegerField(blank=True, default=None, null=True)),
                ('is_done', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, default=None, null=True)),
                ('end', models.TimeField(blank=True, default=None, null=True)),
                ('is_done', models.BooleanField(blank=True, default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.taskday')),
            ],
        ),
    ]
