# Generated by Django 4.1.7 on 2023-03-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskday',
            name='date',
            field=models.DateField(),
        ),
    ]
