# Generated by Django 4.1.7 on 2023-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='note',
            name='date_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
