# Generated by Django 4.1.7 on 2023-03-27 12:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_notecategory_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
