# Generated by Django 4.1.7 on 2023-03-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_alter_note_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='notecategory',
            options={'ordering': ['id']},
        ),
    ]
